### ISSUE TITLE
Change mp3 to wav

### ISSUE THREAD

**Issue by salos1982** [AlmostInteractive/ESP32-S3-Box-3-Voice-Assistant-Sensor-Dock#15]
Hi,

You did great work writing the configuration for the s3box sensor dock. I have one little request to change mp3 files and play them using HTTP media play to use direct playing sounds (probably in .wav format). It will not be an issue for such short files. But it will make my life easier because the IP of my home assistant server is changed from time to time and I need to change the IP address in configuration.

**Comment by AlmostInteractive** [comment]
If you have a local IP on your LAN like I have, one that won't ever change, then use that.  If for some reason you can't configure a static IP for your LAN devices, I'm not sure there's another route.  `media_player` can only play from a URL.  To play raw waveforms you'd need to take out the `media_player` and put in a `speaker` element instead.  You lose volume control and maybe some other functionality, though.  I guess a last resort option would be to write your own `media_player` component that also incorporates the ability to play raw waveforms like a speaker does, but it seems like figuring out static LAN IPs would be far easier.  😄

**Comment by salos1982** [comment]
Unfortunately, I cannot set static ip in my router

**Comment by AlmostInteractive** [comment]
That seems like a bigger issue for your smart-home.  :-/  If it were me, I think I'd get another router and put my LAN behind that instead.  

I say that because that's exactly what I did; I got a [Ubiquiti EdgeRouterX](https://store.ui.com/us/en/collections/uisp-wired-advanced-routing-compact-poe/products/er-x), put it behind my ISP's crappy, useless modem/router and my entire LAN is behind the ERX.

**Comment by maristieuvelonde** [comment]
While this is obviously fine for the setup in this repo, I really like the sound chimes you've selected and would still prefer wav/flac sources for my needs. Do you know where the chimes came from and if they are available in original lossless formats?
