### ISSUE TITLE
Light sleep

### ISSUE THREAD

**Issue by soulripper13** [AlmostInteractive/ESP32-S3-Box-3-Voice-Assistant-Sensor-Dock#16]
Thanks for the great firmware. I was reading up on light sleep mode for esp32 devices, is there anyway we can implement that in here? It would be great fro battery life.

**Comment by AlmostInteractive** [comment]
Hm, never heard of it.  Looking really quickly, I don't see that light sleep mode has been implemented in ESPHome yet.  It's been [requested as a feature](https://github.com/esphome/feature-requests/issues/141) and it looks like people are doing experiments, but I don't see anything conclusive yet.

It looks like there's a supported [deep sleep component](https://esphome.io/components/deep_sleep.html) that you might be able to integrate, and you could put your WiFi into [high power-saving mode](https://esphome.io/components/wifi.html#power-save-mode) as well.  That might help.
