### ISSUE TITLE
Bad sound quality

### ISSUE THREAD

**Issue by salos1982** [AlmostInteractive/ESP32-S3-Box-3-Voice-Assistant-Sensor-Dock#17]
Hi, I flashed your firmware and found that voice assistant sound is of bad quality. It speeak very fast and I fixed the issue reducing sample rate of media player. However overall quality is much worse that I had using speaker with default firmware.

**Comment by AlmostInteractive** [comment]
How does it compare to other ESPHome projects using a `media_player` component?  Turning the `media_player` `sample_rate` to `16000` did fix the speed issue though.  Thanks!  :)

**Comment by salos1982** [comment]
The default implementation of voice assistant uses a speaker and it sound more clear then your implementation using media player

**Comment by salos1982** [comment]
It seems after the update of esphome quality becomes much better
