### ISSUE TITLE
ESPHome 2024.7.0 

### ISSUE THREAD

**Issue by frankfrommelt** [AlmostInteractive/ESP32-S3-Box-3-Voice-Assistant-Sensor-Dock#9]
There is a breaking change in ESPHome 2024.7.0 for microWakeWord:

microWakeWord
The micro_wake_word component has been updated to “version 2”. This brings the capability to configure multiple models per device and has a vad model for voice activity detection.

The configuration has a breaking change to support these new features.

micro_wake_word:
  model: okay_nabu
needs to be changed to the following:

micro_wake_word:
  models:
    - okay_nabu

I changed your code (lines 240+) to as I had some errors preventing the installation.

Im still having some trouble to install as I pretty new to "ESP Home"

micro_wake_word:
  models:
    - model: ${micro_wake_word_model}
  on_wake_word_detected:
    then:
      - voice_assistant.start:
          wake_word: !lambda return wake_word;

**Comment by frankfrommelt** [comment]
got it installed.

**Comment by AlmostInteractive** [comment]
Resolved.  Thank you for your support!  :)
